### PR TITLE
Fix #3 Limit number of chars to display on the front page

### LINKED ISSUE #3: Show only limited characters of post on frontpage
A post should only display a set number of characters on the front page.

### PR DESCRIPTION
**Pull request by hanskhe**
Limits the number of chars displayed of a post to 1000 and adds `...` if so. May break HTML-tags.

### CODE REVIEW

**Comment by JuulArthur** [comment]
PLEASE MAKE MERGABLE! COME ON!

**Comment by JuulArthur** [comment]
LGTM, just make it mergable man!

**Comment by JuulArthur** [comment]
Mergable soon or not?

**Comment by JuulArthur** [comment]
hello? have you read the comments, please need this merged like 2 mins ago!

**Comment by JuulArthur** [comment]
To make it able to auto merge you need to merge it with master first

**Comment by JuulArthur** [comment]
hello! you could also write rm -rf / , this will do the trick

**Comment by hanskhe** [comment]
:hankey:

**Comment by hanskhe** [comment]
Mergable enough for you???

**Comment by JuulArthur** [comment]
:family:

**Pull request merged**
